networks:
  db_internal:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.15.0/30
          gateway: "192.168.15.1"
  es_internal:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.15.4/30
          gateway: "192.168.15.5"
services:
  db01:
    image: angy91m/percx:8.0.34
    container_name: db01
    ports:
      - ${SELF_IP}:3306:3306
      - ${SELF_IP}:4567:4567
      - ${SELF_IP}:4568:4568
      - ${SELF_IP}:4444:4444
    env_file:
      - .env.db
    environment:
      MYSQL_DATABASE: wiki_db
    networks:
      db_internal:
        ipv4_address: "192.168.15.2"
    volumes:
      - ./db-start.sh:/start.sh
      - ./xtra.cnf:/home/mysql/xtra.cnf:ro
      - ./db-data/data:/data/mysql
      - ./db-data/binlog:/data/binlog
      - ./db-data/log:/var/log/mysql
    entrypoint: ["/start.sh"]
    secrets:
      - db-password
      - db-bck-password
  es01:
    image: elasticsearch:8.13.0
    container_name: es01
    ports:
      - ${SELF_IP}:9200:9200
      - ${SELF_IP}:9300:9300
    environment:
      node.name: es01
      cluster.name: es-cluster
      #cluster.initial_master_nodes: es01
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      xpack.security.transport.ssl.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      cluster.routing.allocation.disk.threshold_enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD_FILE: /run/secrets/elastic-password
    networks:
      es_internal:
        ipv4_address: "192.168.15.6"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic-data:/usr/share/elasticsearch/data
      - ./_italian_stop_:/usr/share/elasticsearch/config/_italian_stop_
    secrets:
      - elastic-password
secrets:
  elastic-password:
    file: ./elastic-password
  db-password:
    file: ./db-password
  db-bck-password:
    file: ./db-bck-password