networks:
  db_net:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.15.0/29
          gateway: "192.168.15.1"
  es_net:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.15.8/29
          gateway: "192.168.15.9"
  strapi_net:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.15.16/29
          gateway: "192.168.15.17"
  proxy_net:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.15.24/29
          gateway: "192.168.15.25"
services:
  db01:
    image: mariadb:11.3.2
    container_name: db01
    env_file:
      - .env.mariadb
    environment:
      MARIADB_DATABASE: wiki_db
    networks:
      db_net:
        ipv4_address: "192.168.15.2"
    volumes:
      - ./mariadb-start.sh:/start.sh
      - ./mariadb.cnf:/mariadb.cnf:ro
      - ./db-data:/var/lib/mysql:Z
    entrypoint: ["/start.sh"]
    secrets:
      - db-password
      - db-bck-password
  es01:
    image: elasticsearch:8.13.0
    container_name: es01
    environment:
      node.name: es01
      network.host: _local_
      cluster.name: es-cluster
      #cluster.initial_master_nodes: es01
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      xpack.security.transport.ssl.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      cluster.routing.allocation.disk.threshold_enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD_FILE: /run/secrets/elastic-password
    networks:
      es_net:
        ipv4_address: "192.168.15.10"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic-data:/usr/share/elasticsearch/data
      - ./elastic-confdir/_italian_stop_:/usr/share/elasticsearch/config/_italian_stop_
      - ./elastic-confdir/indexes:/usr/share/elasticsearch/config/indexes
      - ./elastic-confdir/start.sh:/start.sh
    command: -- /start.sh
    secrets:
      - elastic-password
  strapi:
    image: node:20-alpine
    container_name: strapi
    user: node
    working_dir: /home/node/app
    volumes:
      - ../strapi-wiki:/home/node/app
    expose:
      - "1337"
    networks:
      strapi_net:
        ipv4_address: "192.168.15.18"
      db_net:
        ipv4_address: "192.168.15.3"
      es_net:
        ipv4_address: "192.168.15.11"
    environment:
      NPM_CONFIG_PREFIX: /home/node/.npm-global
    command: |
      PATH="$PATH:/home/node/.npm-global/bin" echo "$PATH" && \
      npm i -g node-gyp && \
      npm i -g cargo-cp-artifact && \
      yarn install && yarn develop
  proxy:
    image: nginx:1.25.5-alpine
    container_name: proxy
    ports:
      - ${SELF_IP}:80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      proxy_net:
        ipv4_address: "192.168.15.26"
      es_net:
        ipv4_address: "192.168.15.12"
      strapi_net:
        ipv4_address: "192.168.15.19"
  # redis:
  #   image: redis:7.2.4-alpine
  #   container_name: redis
  #   ports:
  #     - ${SELF_IP}:6379:6379
  #   networks:
  #     redis_internal:
  #       ipv4_address: "192.168.15.10"
  #   command: redis-server --save ""
secrets:
  elastic-password:
    file: ./elastic-confdir/elastic-password
  db-password:
    file: ./db-password
  db-bck-password:
    file: ./db-bck-password
