services:
  es01:
    image: elasticsearch:8.13.0
    container_name: es01
    ports:
      - 192.168.216.0:9200:9200
      - 192.168.216.0:9300:9300
    environment:
      node.name: es01
      cluster.name: es-cluster
      #cluster.initial_master_nodes: es01
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      xpack.security.transport.ssl.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      cluster.routing.allocation.disk.threshold_enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD_FILE: /run/secrets/elastic-password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic-data:/usr/share/elasticsearch/data
      - ./_italian_stop_:/usr/share/elasticsearch/config/_italian_stop_
    secrets:
      - elastic-password
secrets:
  elastic-password:
    file: ./elastic-password