networks:
  db_internal:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.15.0/30
          gateway: "192.168.15.1"
  es_internal:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.15.4/30
          gateway: "192.168.15.5"
  proxy_internal:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.15.8/30
          gateway: "192.168.15.9"
services:
  db01:
    image: mariadb:11.3.2
    container_name: db01
    ports:
      - 127.0.0.1:3306:3306
    env_file:
      - .env.mariadb
    environment:
      MARIADB_DATABASE: wiki_db
    networks:
      db_internal:
        ipv4_address: "192.168.15.2"
    volumes:
      - ./mariadb-start.sh:/start.sh
      - ./mariadb.cnf:/mariadb.cnf:ro
      - ./db-data:/var/lib/mysql:Z
    entrypoint: ["/start.sh"]
    secrets:
      - db-password
      - db-bck-password
  es01:
    image: elasticsearch:8.13.0
    container_name: es01
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      node.name: es01
      network.host: es01.wikilina.loc
      cluster.name: es-cluster
      #cluster.initial_master_nodes: es01
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      xpack.security.transport.ssl.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      cluster.routing.allocation.disk.threshold_enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD_FILE: /run/secrets/elastic-password
    networks:
      es_internal:
        ipv4_address: "192.168.15.6"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic-data:/usr/share/elasticsearch/data
      - ./_italian_stop_:/usr/share/elasticsearch/config/_italian_stop_
    secrets:
      - elastic-password
  proxy:
    image: nginx:1.25.5-alpine
    container_name: proxy
    ports:
      - ${SELF_IP}:80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      proxy_internal:
        ipv4_address: "192.168.15.10"
  # redis:
  #   image: redis:7.2.4-alpine
  #   container_name: redis
  #   ports:
  #     - ${SELF_IP}:6379:6379
  #   networks:
  #     redis_internal:
  #       ipv4_address: "192.168.15.10"
  #   command: redis-server --save ""
secrets:
  elastic-password:
    file: ./elastic-password
  db-password:
    file: ./db-password
  db-bck-password:
    file: ./db-bck-password
